apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cw2-server
  template:
    metadata:
      labels:
        app: cw2-server
    spec:
      containers:
        - name: cw2-server
          image: abhiwable4/cw2-server:1.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cw2-service
spec:
  type: LoadBalancer
  selector:
    app: cw2-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
