---
- name: Setup Minikube Kubernetes cluster on production server
  hosts: production
  become: yes

  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - conntrack
          - socat
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Verify kubectl installation
      command: kubectl version --client=true
      register: kubectl_version
      changed_when: false

    - name: Show kubectl version
      debug:
        var: kubectl_version.stdout

    - name: Download Minikube binary
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Start Minikube with Docker driver and force flag
      command: minikube start --driver=docker --force
      args:
        creates: /root/.minikube
